-- Dhakefile.dhall — build the shen-meta fixpoint-design docs site with dhake.
--
-- The C VM (vm/*.c) has its own Makefile (make / make test / make bundle) and
-- is NOT rebuilt here; the wasm VM module (docs/shen-wasm.js + docs/shen-wasm.wasm)
-- is committed and regenerated by scripts/build-wasm.sh (needs emscripten).
-- This buildfile drives the docs site at fixpointlinux.org/shen:
--
--     vendor/mfe-framework -> vendor/@mfe -> dist/elm.js -> dist/index.html
--
-- Run with dhake from this directory:
--
--     ./vendor/dhake/dhake.com                    # default: `all`
--     ./vendor/dhake/dhake.com all
--     ./vendor/dhake/dhake.com dist/index.html    # build the docs site
--     ./vendor/dhake/dhake.com --list             # list all targets

let Action =
      < Shell : Text
      | Copy : { from : Text, to : Text }
      | Mkdir : < Plain : Text | Parents : { path : Text, parents : Bool } >
      | Rm : < Plain : Text | Recursive : { path : Text, recursive : Bool } >
      | Touch : Text
      | Move : { from : Text, to : Text }
      | Symlink : { from : Text, to : Text }
      | Chmod : { path : Text, mode : Text }
      | Echo : Text
      | Env : { key : Text, value : Text }
      | Run : { argv : List Text }
      >

let Target = { deps : List Text, phony : Bool, recipe : List Action
             , hash : Optional Text
             , depsHash : Optional (List { path : Text, hash : Text })
             , arch : Optional Text
             }

in  { targets =
        -- ─── docs site (fixpoint design components) ─────────────────────────
        -- The docs site is an Elm app (src/Main.elm) rendered against the shared
        -- Fixpoint.* design package (vendor/design) + the @mfe/framework shell
        -- (vendor/mfe-framework). Pipeline, mirroring datalog-dafsa:
        --
        --   vendor/mfe-framework -> vendor/@mfe -> dist/elm.js -> dist/index.html
        --
        -- The `dist/index.html` target produces the full multi-route site
        -- (dist/index.html + the four sub-page index.html files + the
        -- wasm/xterm assets copied by scripts/ssg.mjs from docs/). Run it
        -- explicitly with `dhake dist/index.html`. The site does not require
        -- emscripten (wasm is committed to docs/ and copied by the ssg).
        [ { mapKey = "mfe-framework"
          , mapValue =
              { deps = []
              , phony = True
              , recipe =
                  [ < Shell = "cd vendor/mfe-framework && npm ci && npm run build" >
                  ]
              }
          }
        , { mapKey = "vendor-mfe"
          , mapValue =
              { deps = [ "mfe-framework" ]
              , phony = True
              , recipe =
                  [ < Rm = { path = "vendor/@mfe", recursive = True } >
                  , < Mkdir = { path = "vendor/@mfe/core", parents = True } >
                  , < Mkdir = { path = "vendor/@mfe/framework", parents = True } >
                  , < Shell =
                        "cp vendor/mfe-framework/packages/core/dist/*.js vendor/@mfe/core/"
                    >
                  , < Shell =
                        "cp vendor/mfe-framework/packages/framework/dist/*.js vendor/@mfe/framework/"
                    >
                  ]
              }
          }
        , { mapKey = "dist/elm.js"
          , mapValue =
              { deps = [ "src/Main.elm", "elm.json", "vendor/design/src" ]
              , phony = False
              , recipe =
                  [ < Shell =
                        "node_modules/elm/bin/elm make src/Main.elm --output=dist/elm.js --optimize"
                    >
                  ]
              }
          }
        , { mapKey = "dist/index.html"
          , mapValue =
              { deps =
                  [ "dist/elm.js"
                  , "vendor-mfe"
                  , "shell/index.html"
                  , "shell/pages.js"
                  , "shell/shell.js"
                  , "shell/templates/shen-landing.html"
                  , "shell/templates/shen-architecture.html"
                  , "shell/templates/shen-build.html"
                  , "shell/templates/shen-primitives.html"
                  , "shell/templates/shen-playground.html"
                  , "shell/templates/fixpoint.html"
                  , "shell/mfe/shen-page.js"
                  , "shell/mfe/shen-playground.js"
                  , "scripts/ssg.mjs"
                  , "docs/shen-wasm.js"
                  , "docs/shen-wasm.wasm"
                  , "docs/vendor/xterm/xterm.js"
                  , "docs/vendor/xterm/xterm.css"
                  ]
              , phony = False
              , recipe = [ < Shell = "node scripts/ssg.mjs" > ]
              }
          }
        ]
      , default = "all"
      }
