/* Auto-generated by tools/qbe-gen-prims.awk from vm/qbe-prims.list.
 * prim_<F> wrappers: dispatch the primitive through the REAL
 * exec_primitive with the ZINC RTL-push arg convention (a1=leftmost).
 * Do not edit by hand. */
#ifndef QBE_PRIMS_GEN_H
#define QBE_PRIMS_GEN_H

#include "zincvm.h"

void prim_fst(Value *out, Value *a1);
void prim_shen_str_to_bytes(Value *out, Value *a1);
void prim_error_p(Value *out, Value *a1);
void prim_empty_p(Value *out, Value *a1);
void prim_assoc(Value *out, Value *a1, Value *a2);
void prim_cn(Value *out, Value *a1, Value *a2);
void prim_le(Value *out, Value *a1, Value *a2);
void prim_substring(Value *out, Value *a1, Value *a2, Value *a3);
void prim_n_to_string(Value *out, Value *a1);
void prim_hdstr(Value *out, Value *a1);
void prim_stinput(Value *out);
void prim_absvector_p(Value *out, Value *a1);
void prim_lt(Value *out, Value *a1, Value *a2);
void prim_mul(Value *out, Value *a1, Value *a2);
void prim_nth(Value *out, Value *a1, Value *a2);
void prim_tl(Value *out, Value *a1);
void prim_string_p(Value *out, Value *a1);
void prim_snd(Value *out, Value *a1);
void prim_minus(Value *out, Value *a1, Value *a2);
void prim_newvar(Value *out, Value *a1);
void prim_simple_error(Value *out, Value *a1);
void prim_read_byte(Value *out, Value *a1);
void prim_write_byte(Value *out, Value *a1, Value *a2);
void prim_from_address(Value *out, Value *a1, Value *a2);
void prim_char_code(Value *out, Value *a1, Value *a2);
void prim_tlstr(Value *out, Value *a1);
void prim_pos(Value *out, Value *a1, Value *a2);
void prim_variable_p(Value *out, Value *a1);
void prim_eq(Value *out, Value *a1, Value *a2);
void prim_gensym(Value *out, Value *a1);
void prim_get_time(Value *out, Value *a1);
void prim_open(Value *out, Value *a1, Value *a2);
void prim_stream_p(Value *out, Value *a1);
void prim_trap_error(Value *out, Value *a1, Value *a2);
void prim_absvector(Value *out, Value *a1);
void prim_string_to_n(Value *out, Value *a1);
void prim_div(Value *out, Value *a1, Value *a2);
void prim_shen_fail_bang(Value *out, Value *a1);
void prim_intern(Value *out, Value *a1);
void prim_address_to(Value *out, Value *a1, Value *a2, Value *a3);
void prim_ge(Value *out, Value *a1, Value *a2);
void prim_length(Value *out, Value *a1);
void prim_hd(Value *out, Value *a1);
void prim_value(Value *out, Value *a1);
void prim_close(Value *out, Value *a1);
void prim_shen_bytes_to_string(Value *out, Value *a1);
void prim_symbol_p(Value *out, Value *a1);
void prim_plus(Value *out, Value *a1, Value *a2);
void prim_reverse(Value *out, Value *a1);
void prim_cons(Value *out, Value *a1, Value *a2);
void prim_element_p(Value *out, Value *a1, Value *a2);
void prim_atp(Value *out, Value *a1, Value *a2);
void prim_eval_kl(Value *out, Value *a1);
void prim_error_to_string(Value *out, Value *a1);
void prim_read_file_as_string(Value *out, Value *a1);
void prim_c_strlen(Value *out, Value *a1);
void prim_gt(Value *out, Value *a1, Value *a2);
void prim_append(Value *out, Value *a1, Value *a2);
void prim_fail(Value *out, Value *a1);
void prim_set(Value *out, Value *a1, Value *a2);
void prim_stoutput(Value *out);
void prim_emptylist(Value *out, Value *a1);
void prim_str(Value *out, Value *a1);
void prim_function_p(Value *out, Value *a1);
void prim_cons_p(Value *out, Value *a1);
void prim_boolean_p(Value *out, Value *a1);
void prim_number_p(Value *out, Value *a1);

#endif /* QBE_PRIMS_GEN_H */
