/* Auto-generated by tools/qbe-gen-prims.awk from vm/qbe-prims.list.
 * Do not edit by hand. */
#include "qbe_shims.h"

void prim_fst(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("fst", 1, out, args); }
void prim_shen_str_to_bytes(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("shen.str->bytes", 1, out, args); }
void prim_error_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("error?", 1, out, args); }
void prim_empty_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("empty?", 1, out, args); }
void prim_assoc(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("assoc", 2, out, args); }
void prim_cn(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("cn", 2, out, args); }
void prim_le(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("<=", 2, out, args); }
void prim_substring(Value *out, Value *a1, Value *a2, Value *a3) { Value *args[3] = { a1, a2, a3 }; prim_dispatch("substring", 3, out, args); }
void prim_n_to_string(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("n->string", 1, out, args); }
void prim_hdstr(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("hdstr", 1, out, args); }
void prim_stinput(Value *out) { prim_dispatch("stinput", 0, out, NULL); }
void prim_absvector_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("absvector?", 1, out, args); }
void prim_lt(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("<", 2, out, args); }
void prim_mul(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("*", 2, out, args); }
void prim_nth(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("nth", 2, out, args); }
void prim_tl(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("tl", 1, out, args); }
void prim_string_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("string?", 1, out, args); }
void prim_snd(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("snd", 1, out, args); }
void prim_minus(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("-", 2, out, args); }
void prim_newvar(Value *out) { prim_dispatch("newvar", 0, out, NULL); }
void prim_simple_error(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("simple-error", 1, out, args); }
void prim_read_byte(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("read-byte", 1, out, args); }
void prim_write_byte(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("write-byte", 2, out, args); }
void prim_from_address(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("<-address", 2, out, args); }
void prim_char_code(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("char-code", 2, out, args); }
void prim_tlstr(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("tlstr", 1, out, args); }
void prim_pos(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("pos", 2, out, args); }
void prim_variable_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("variable?", 1, out, args); }
void prim_eq(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("=", 2, out, args); }
void prim_gensym(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("gensym", 1, out, args); }
void prim_get_time(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("get-time", 1, out, args); }
void prim_open(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("open", 2, out, args); }
void prim_stream_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("stream?", 1, out, args); }
void prim_trap_error(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("trap-error", 2, out, args); }
void prim_absvector(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("absvector", 1, out, args); }
void prim_string_to_n(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("string->n", 1, out, args); }
void prim_div(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("/", 2, out, args); }
void prim_shen_fail_bang(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("shen.fail!", 1, out, args); }
void prim_intern(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("intern", 1, out, args); }
void prim_address_to(Value *out, Value *a1, Value *a2, Value *a3) { Value *args[3] = { a1, a2, a3 }; prim_dispatch("address->", 3, out, args); }
void prim_ge(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch(">=", 2, out, args); }
void prim_length(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("length", 1, out, args); }
void prim_hd(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("hd", 1, out, args); }
void prim_value(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("value", 1, out, args); }
void prim_close(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("close", 1, out, args); }
void prim_shen_bytes_to_string(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("shen.bytes->string", 1, out, args); }
void prim_symbol_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("symbol?", 1, out, args); }
void prim_plus(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("+", 2, out, args); }
void prim_reverse(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("reverse", 1, out, args); }
void prim_cons(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("cons", 2, out, args); }
void prim_element_p(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("element?", 2, out, args); }
void prim_atp(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("@p", 2, out, args); }
void prim_eval_kl(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("eval-kl", 1, out, args); }
void prim_error_to_string(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("error-to-string", 1, out, args); }
void prim_read_file_as_string(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("read-file-as-string", 1, out, args); }
void prim_c_strlen(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("c-strlen", 1, out, args); }
void prim_gt(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch(">", 2, out, args); }
void prim_append(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("append", 2, out, args); }
void prim_fail(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("fail", 1, out, args); }
void prim_set(Value *out, Value *a1, Value *a2) { Value *args[2] = { a1, a2 }; prim_dispatch("set", 2, out, args); }
void prim_stoutput(Value *out) { prim_dispatch("stoutput", 0, out, NULL); }
void prim_emptylist(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("emptylist", 1, out, args); }
void prim_str(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("str", 1, out, args); }
void prim_function_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("function?", 1, out, args); }
void prim_cons_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("cons?", 1, out, args); }
void prim_boolean_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("boolean?", 1, out, args); }
void prim_number_p(Value *out, Value *a1) { Value *args[1] = { a1 }; prim_dispatch("number?", 1, out, args); }
