/* symbol_static.h — auto-generated by tools/gen-symbol-static.py. DO NOT EDIT.
 * Static symbol intern table for the closed-world (subset/meta-interp) bundle.
 * N=1109 symbols, minimal-perfect-hash: index=(h(name,H1)%N + g[h(name,H2)%369])%N.
 */
#ifndef SYMBOL_STATIC_H
#define SYMBOL_STATIC_H

#define SYMBOL_STATIC_N 1109
#define SYMBOL_STATIC_M 369
#define SYMBOL_STATIC_H1 0x9E3779B9u
#define SYMBOL_STATIC_H2 0x9E3779B9u

/* Return the canonical char* for `name` if it is a static (bundle) symbol,
   else NULL.  The returned pointer is a static-lifetime array element, so it
   is a stable, unique identity for the name (pointer-eq == strcmp-eq). */
const char *symbol_static_lookup(const char *name);

#endif
