(tc -)
\* =============================================================================
   serialize-qbe.shen - walk the reduced bundle's global-table and emit QBE IR
   for the static closures (Slice 3).

   Parallel to serialize-reduced.shen: same shen-load sequence builds the same
   full-arity closures in global-table.  Instead of nat->csexp, each closure is
   lowered via qbe.shen's `lower` (over compile-zinc output) to a QBE function
   `function $clo_<name>(...)`, plus the shared data-literal section.

   The closure-selection set is the authoritative first-order partition
   shen/qbe-first-order.shen (generated by `make gen-qbe-subset` from
   tools/bundle-verify/out/first_order.csv = the sound QBE-compilable set).
   `lower` raises a catchable simple-error on the constructs still deferred to
   Slice 5 (cur / trap-error / dynamic apply), so qbe-lower-try skips those
   closures rather than emitting invalid QBE.

   Usage:  shen-scheme script shen/serialize-qbe.shen  ->  globals.qbe
   ============================================================================= *\

\* Load the generated primitive tables (primitive?-names and the QBE
   prim-name->mangle->arity table). *\
(load "shen/prims-generated.shen")
(load "shen/qbe-prim-info.shen")

(load "shen/interp.shen")
(load "shen/set-toplevel.shen")
(tc -)
(load "shen/compile.shen")
(load "shen/load.shen")
(tc -)
(load "shen/shen-kl-helpers.shen")
(load "shen/shen->kl.shen")
(load "shen/qbe-subset.shen")
\* The authoritative first-order partition (generated by `make gen-qbe-subset`).
   This IS the closure-selection set — qbe-roots was a 6-name manual stand-in
   that is now replaced by the full first_order.csv partition. *\
(load "shen/qbe-first-order.shen")
(load "shen/qbe.shen")

\* === Compile .shen files through our own full-arity compiler (as
   serialize-reduced.shen).  Includes the HM type-checker files so the
   global-table matches the reduced bundle the partition was extracted from. === *\
(tc -)
(define shen-eval-forms
  [] -> loaded
  [F | R] -> (do (interp-eval F) (shen-eval-forms R)))
(define shen-load
  Path -> (shen-eval-forms (shen->kl-forms (shen-read-file Path))))
(tc +)

(shen-load "shen/util.shen")
(shen-load "shen/types.shen")
(shen-load "shen/zinc.shen")
(shen-load "shen/compile.shen")
(shen-load "shen/normalize.shen")
(shen-load "shen/primitives.shen")
(shen-load "shen/interp.shen")
(shen-load "shen/toplevel.shen")
(shen-load "shen/load.shen")
(shen-load "shen/os-helpers.shen")
(shen-load "shen/shen-kl-helpers.shen")
(shen-load "shen/shen->kl.shen")

\* === HM type checker (safe-subset; all compile through shen->kl) ===
   Loaded so serialize-qbe's global-table matches the reduced bundle
   (serialize-reduced.shen) that out/first_order.csv was extracted from —
   otherwise the first-order partition (which includes the tc-hm closures)
   selects nothing for them. *\
(shen-load "shen/tc-hm-types.shen")
(shen-load "shen/tc-hm-w.shen")
(shen-load "shen/tc-hm-prims.shen")
(shen-load "shen/tc-hm-patterns.shen")
(shen-load "shen/tc-hm-sig.shen")
(shen-load "shen/tc-hm.shen")
(shen-load "shen/tc-hm-runtime.shen")
(shen-load "shen/tc-hm-tests.shen")

\* === Safe-wrapper alias for `+` (the Test 1 entry).  Point the bare name `+`
   at the safe.+ closure (same object), so the QBE driver can call @clo_plus. === *\
(tc -)
(define install-plus-alias
  -> (do
    (set global-table (cons [+ (lookup-global safe.+)] (value global-table)))
    aliases-installed))
(install-plus-alias)
(tc +)

\* === Add shen. prefix aliases (matches serialize-reduced.shen). === *\
(tc -)
(define shen.has-dot?
  "" -> false
  S -> (if (= "." (hdstr S)) true (shen.has-dot? (tlstr S))))
(define shen.add-prefix-aliases
  [] -> aliases-added
  [[Name Closure] | Rest] -> (do
    (if (shen.has-dot? (str Name))
        shen.skip
        (set global-table (cons [(intern (cn "shen." (str Name))) Closure]
                                (value global-table))))
    (shen.add-prefix-aliases Rest)))
\* dedupe-globals MUST run BEFORE shen.add-prefix-aliases (matching
   serialize-reduced.shen): without dedupe first, add-prefix-aliases creates
   shen.X aliases for BOTH the shen-load'd (our static full-arity) AND the
   set-toplevel'd (host `ps` → shen-scheme-compiled, higher-order) copies of
   each bare name.  The set-toplevel'd alias is prepended LAST → lands at front
   → dedupe keeps it → `lower` sees the host-compiled closure (with
   shen.f-error / dynamic applies / real cur opcodes) instead of our static
   one.  Dedupe first so each bare name survives exactly once (the shen-load'd
   static copy), and its shen. alias maps to it. *\
(set global-table (dedupe-globals (value global-table)))
(shen.add-prefix-aliases (value global-table))
(tc +)

\* === Emit QBE for the linkable-closed subset of the first-order partition. === *\

\* All deduped closure names - the `global G` classification set. *\
(set qbe-table (dedupe-globals (value global-table)))

(define qbe-name-list
  [] -> []
  [[N _] | R] -> [N | (qbe-name-list R)])

(set qbe-all-names (qbe-name-list (value qbe-table)))

\* The selection source is the authoritative first-order partition
   (shen/qbe-first-order.shen, generated by `make gen-qbe-subset` from
   tools/bundle-verify/out/first_order.csv).  The 6 differential driver roots
   (+, reverse, reverse-help, factorial, qbe-sub2, qbe-let-test) are members,
   so Tests 1-5 still emit. *\
(if (bound? qbe-first-order-closures)
    nop
    (simple-error "serialize-qbe: shen/qbe-first-order.shen not loaded — run `make gen-qbe-subset` first"))

\* ---------------------------------------------------------------------------
   Linkable-closed selection.

   The partition (921 closures) is the sound QBE-COMPILABLE set, but NOT every
   member can be emitted into globals.qbe right now:

     - `lower` raises a catchable simple-error on the constructs still
       deferred to Slice 5 (cur / trap-error / dynamic apply); qbe-lower-try
       skips those closures (returns "").
     - A closure that CALLS such a skipped closure would reference a $clo_<name>
       symbol that is never defined -> a dangling reference -> linker error.

   So we emit the MAXIMAL subset of the partition whose call graph is closed:
   every emitted closure's callees are also emitted.  This is a fixed point
   over callees: start with the cur/trap-error closures that fail to lower,
   then repeatedly drop any closure that (transitively) calls one of them.
   The 6 driver roots survive (their callees are all lowerable prims), so the
   differential tests still pass.  Closures dropped here are the Slice-5
   deferred set (cur/trap-error + everything that depends on them).
   --------------------------------------------------------------------------- *\

\* lower wrapped in trap-error: unsupported constructs (cur / dynamic apply)
   raise a catchable simple-error; skip those closures.  `lower` resets its own
   (value qbe-datas) at entry, so accumulate each closure's data literals into
   a shared list. *\
(set qbe-all-datas [])
(set qbe-all-extra-fns [])
(set qbe-all-trap-shims [])

(define qbe-lower-try { symbol --> klambda --> string }
  N Code -> (trap-error
              (let Fn (lower N Code (value qbe-all-names))
                (do (set qbe-all-datas (append (value qbe-datas) (value qbe-all-datas)))
                    (set qbe-all-extra-fns (append (value qbe-extra-fns) (value qbe-all-extra-fns)))
                    (set qbe-all-trap-shims (append (value qbe-trap-shims) (value qbe-all-trap-shims)))
                    Fn))
              (lambda E "")))

\* Candidates: [N CompiledZinc] for every closure in the partition that is
   static, pre-compiled once so `lower` (emission) and callee extraction share
   the same flat zinc stream. *\
(define qbe-candidates { (list (list symbol zinc-value)) --> (list (list symbol klambda)) }
  [] -> []
  [[N [lambda Code []]] | R] ->
    (if (and (element? N (value qbe-first-order-closures))
             (qbe-static-closure? N))
        [[N (compile-zinc Code)] | (qbe-candidates R)]
        (qbe-candidates R))
  [_ | R] -> (qbe-candidates R))

\* Callees: [global G] that `lower` resolves to a [clo G] call — i.e. G is a
   non-primitive bundled closure (a member of qbe-all-names).  These are the
   only link dependencies (prims resolve to C shims, and non-closure globals to
   runtime global_get). *\
(define qbe-callees { klambda --> (list symbol) }
  [] -> []
  [global G | R] ->
    (if (and (not (qbe-prim? G)) (element? G (value qbe-all-names)))
        [G | (qbe-callees R)]
        (qbe-callees R))
  \* Operand-carrying instructions: consume the operand so a bare `global`
     (as the operand of [symbol global], etc.) is not misread as an opcode. *\
  [access _ | R]   -> (qbe-callees R)
  [jmpf _ | R]     -> (qbe-callees R)
  [jmp _ | R]      -> (qbe-callees R)
  [number _ | R]   -> (qbe-callees R)
  [string _ | R]   -> (qbe-callees R)
  [symbol _ | R]   -> (qbe-callees R)
  [boolean _ | R]  -> (qbe-callees R)
  [prim _ | R]     -> (qbe-callees R)
  \* Recurse into cur bodies: the defunctionalized body's `[global G]` resolves
     to a $clo_G call, so G is a link dependency of the enclosing closure. *\
  [cur C1 | R]     -> (append (qbe-callees C1) (qbe-callees R))
  [_ | R] -> (qbe-callees R))

(define qbe-has-skipped-callee { klambda --> (list symbol) --> boolean }
  Code Skipped -> (qbe-has-skipped-callee-h (qbe-callees Code) Skipped))
(define qbe-has-skipped-callee-h { (list symbol) --> (list symbol) --> boolean }
  [] _ -> false
  [G | R] Skipped -> (if (element? G Skipped) true (qbe-has-skipped-callee-h R Skipped)))

\* Does this closure lower successfully?  (probe; discarded output) *\
(define qbe-lowerable? { symbol --> klambda --> boolean }
  N Code -> (trap-error (do (lower N Code (value qbe-all-names)) true) (lambda E false)))

\* Initial skipped set = candidates that fail to lower (cur/trap-error / dynamic
   apply — the Slice-5 deferred constructs).  The qbe-rega-blacklist was
   REMOVED 2026-08-19: vendor/qbe was updated to latest upstream (4420727),
   which fixes the rega.c Assertion `x != -1` on wide phi live-ranges, so the
   HM-typechecker closures now assemble natively.  qbe-prune drops the failures
   and any transitive callers. *\

(define qbe-skipped0 { (list (list symbol klambda)) --> (list symbol) }
  [] -> []
  [[N Code] | R] ->
    (if (not (qbe-lowerable? N Code))
        (cons N (qbe-skipped0 R))
        (qbe-skipped0 R)))

\* Fixed point: repeatedly add any candidate that (transitively) calls a
   skipped closure, until stable. *\
(set qbe-changed false)
(define qbe-prune-step { (list (list symbol klambda)) --> (list symbol) --> (list symbol) }
  [] Skipped -> Skipped
  [[N Code] | R] Skipped ->
    (if (element? N Skipped)
        (qbe-prune-step R Skipped)
        (if (qbe-has-skipped-callee Code Skipped)
            (do (set qbe-changed true)
                (qbe-prune-step R (cons N Skipped)))
            (qbe-prune-step R Skipped))))
(define qbe-prune { (list (list symbol klambda)) --> (list symbol) --> (list symbol) }
  Candidates Skipped ->
    (do (set qbe-changed false)
      (let NewS (qbe-prune-step Candidates Skipped)
        (if (value qbe-changed) (qbe-prune Candidates NewS) NewS))))

\* Emit the survivors (closures not in the final skipped set). *\
(define qbe-emit-list { (list (list symbol klambda)) --> (list symbol) --> string }
  [] _ -> ""
  [[N Code] | R] Skipped ->
    (if (element? N Skipped)
        (qbe-emit-list R Skipped)
        (cn (qbe-lower-try N Code) (qbe-emit-list R Skipped))))

(set qbe-cands (qbe-candidates (value qbe-table)))
(set qbe-skipped (qbe-prune (value qbe-cands) (qbe-skipped0 (value qbe-cands))))
(set qbe-fns (qbe-emit-list (value qbe-cands) (value qbe-skipped)))

\* Render the defunctionalized trap-shim registrations as "T1 T2 Ncap" lines,
   consumed by tools/qbe-gen-traps.awk -> globals_trap.c. *\
(define qbe-trap-list-str { (list (list number number number)) --> string }
  [] -> ""
  [[T1 T2 Ncap] | R] ->
    (cn (cn (cn (str T1) " ") (cn (str T2) (cn " " (str Ncap))))
        (cn (value qbe-nl) (qbe-trap-list-str R))))

(set *qbe* (cn (qbe-datas-str (value qbe-all-datas))
               (cn (value qbe-fns) (qbe-join (value qbe-all-extra-fns)))))

(set *out* (open "globals.qbe" out))
(pr (value *qbe*) (value *out*))
(close (value *out*))

(set *trap-list* (qbe-trap-list-str (value qbe-all-trap-shims)))
(set *tout* (open "globals_trap.list" out))
(pr (value *trap-list*) (value *tout*))
(close (value *tout*))
