# qbe-gen-prims.awk — generate the QBE prim_<F> C shims and the Shen info table
# from vm/qbe-prims.list (single source of truth).
#
# Usage:
#   awk -f tools/qbe-gen-prims.awk vm/qbe-prims.list
#
# Emits three files (written via stdout redirection from the Makefile):
#   vm/qbe_prims_gen.h    — declarations  (void prim_<mangled>(...))
#   vm/qbe_prims_gen.c    — definitions   (dispatch through prim_dispatch)
#   shen/qbe-prim-info.shen — (set qbe-prim-info [[orig mangled arity] ...])

BEGIN {
    hdr = "vm/qbe_prims_gen.h"
    src = "vm/qbe_prims_gen.c"
    shn = "shen/qbe-prim-info.shen"
}

# Skip comments and blank lines.
/^[[:space:]]*(#|$)/ { next }

{
    orig = $1
    mangle = $2
    arity = $3

    # Build the C parameter list: (out, a1, a2, a3) up to arity.
    params = "Value *out"
    arglist = ""
    for (i = 1; i <= arity; i++) {
        params = params ", Value *a" i
        if (i > 1) arglist = arglist ", "
        arglist = arglist "a" i
    }

    decls[mangle] = "void prim_" mangle "(" params ");"
    if (arity == 0) {
        defs[mangle] = "void prim_" mangle "(Value *out) { prim_dispatch(\"" orig "\", 0, out, NULL); }"
    } else {
        defs[mangle] = "void prim_" mangle "(" params ") { Value *args[" arity "] = { " arglist " }; prim_dispatch(\"" orig "\", " arity ", out, args); }"
    }

    shen[mangle] = "   [" orig " " mangle " " arity "]"
}

END {
    # Header
    print "/* Auto-generated by tools/qbe-gen-prims.awk from vm/qbe-prims.list." > hdr
    print " * prim_<F> wrappers: dispatch the primitive through the REAL" > hdr
    print " * exec_primitive with the ZINC RTL-push arg convention (a1=leftmost)." > hdr
    print " * Do not edit by hand. */" > hdr
    print "#ifndef QBE_PRIMS_GEN_H" > hdr
    print "#define QBE_PRIMS_GEN_H" > hdr
    print "" > hdr
    print "#include \"zincvm.h\"" > hdr
    print "" > hdr
    for (m in decls) print decls[m] > hdr
    print "" > hdr
    print "#endif /* QBE_PRIMS_GEN_H */" > hdr

    # Source
    print "/* Auto-generated by tools/qbe-gen-prims.awk from vm/qbe-prims.list." > src
    print " * Do not edit by hand. */" > src
    print "#include \"qbe_shims.h\"" > src
    print "" > src
    for (m in defs) print defs[m] > src

    # Shen table
    print "(set qbe-prim-info [" > shn
    for (m in shen) print shen[m] > shn
    print "])" > shn
}
