# qbe-gen-traps.awk — generate the defunctionalized trap-error C shims from
# globals_trap.list (one "T1 T2 ncap" line per pair, emitted by serialize-qbe.shen).
#
# Usage:
#   awk -f tools/qbe-gen-traps.awk globals_trap.list > globals_trap.c
#
# Each shim `trap_<T1>_<T2>` runs the cur body `b_T1` natively under setjmp and,
# on longjmp (an error raised inside the body), runs the handler `b_T2` natively
# with the caught error.  The captured env (cap_0..cap_{ncap-1}) is rooted across
# both calls, and `gc_root_pop_to(wm)` unwinds any roots leaked by the aborted
# prim_dispatch on the error path — exactly matching the C VM trap-error primitive
# (zincvm.c).  `cf.in_trap_error = 1` is set only while running the body so an
# always-on throw (pos OOB, simple-error) inside the body is caught here, while an
# error inside the handler propagates to the enclosing frame (unlinked first).

BEGIN {
    print "/* Auto-generated by tools/qbe-gen-traps.awk from globals_trap.list."
    print " * Defunctionalized trap-error shims.  Do not edit by hand. */"
    print "#include \"zincvm.h\""
    print "#include \"qbe_shims.h\""
    print ""
}

# skip comments and blank lines
/^[[:space:]]*(#|$)/ { next }

{
    t1 = $1; t2 = $2; ncap = $3 + 0

    # extern decls for the two cur-body functions (defined in globals.qbe)
    ext = "extern void b_" t1 "(Value *out, Value *a0"
    for (i = 0; i < ncap; i++) ext = ext ", Value *cap_" i
    print ext ");"
    ext = "extern void b_" t2 "(Value *out, Value *a0"
    for (i = 0; i < ncap; i++) ext = ext ", Value *cap_" i
    print ext ");"
    print ""

    # shim signature
    sig = "void trap_" t1 "_" t2 "(Value *out"
    for (i = 0; i < ncap; i++) sig = sig ", Value *cap_" i
    print sig ") {"
    print "    CatchFrame cf;"
    print "    Value err;"
    for (i = 0; i < ncap; i++) print "    gc_root_push_value(cap_" i ");"
    print "    cf.parent = vm_catch_chain;"
    print "    cf.in_trap_error = 0;"
    print "    vm_catch_chain = &cf;"
    print "    volatile size_t wm = gc_root_watermark();"
    print "    if (setjmp(cf.buf) == 0) {"
    print "        cf.in_trap_error = 1;"
    print "        Value nilv = val_nil();"
    call = "        b_" t1 "(out, &nilv"
    for (i = 0; i < ncap; i++) call = call ", cap_" i
    print call ");"
    print "        vm_catch_chain = cf.parent;"
    print "        gc_root_pop_to(wm);"
    for (i = 0; i < ncap; i++) print "        gc_root_pop();"
    print "        return;"
    print "    } else {"
    print "        vm_catch_chain = cf.parent;"
    print "        gc_root_pop_to(wm);"
    print "        err = cf.error_val;"
    print "        gc_root_push_value(&err);"
    call = "        b_" t2 "(out, &err"
    for (i = 0; i < ncap; i++) call = call ", cap_" i
    print call ");"
    print "        gc_root_pop();"
    for (i = 0; i < ncap; i++) print "        gc_root_pop();"
    print "        return;"
    print "    }"
    print "}"
    print ""
}
